alias jxa='osascript -l JavaScript'
#alias python='python3'
alias ntex='nvim *.tex'
alias jbtex='platex *.tex ; dvipdfmx -V4 *.dvi'
alias texcpl='(){uplatex $1.tex ; dvipdfmx $1.dvi}'
alias skim='open -a /Applications/Skim.app'
alias arduino='open -a /Applications/Arduino.app'
alias python='python3'
alias ls='ls -Gl'
alias d='~/dotfiles'
alias cl='clear'
alias so='source ~/.zshrc'

#git alias
alias g='git'
alias ga='git add'
alias gd='git diff'
alias gs='git status'
alias gp='git push'
alias gb='git branch'
alias gst='git status'
alias gco='git checkout'
alias gf='git fetch'
alias gc='git commit'

#network in mac
alias net_off='sudo networksetup -setairportpower en0 off'
alias net_on='sudo networksetup -setairportpower en0 on'
alias net_ssid='networksetup -setairportnetwork en0'
